name: Healenium CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  healenium-tests:
    runs-on: ubuntu-latest
    services:
      docker:
        image: 'docker:20.10-dind'
        options: '--dns 8.8.8.8 --dns 8.8.4.4'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Start Healenium services
        run: |
          docker-compose -f docker-compose.yml up -d
          docker ps -a
      - name: Wait for Healenium services
        run: |
          echo "Waiting for Healenium services..."
          sleep 120
          docker logs hlm-proxy || true
          docker logs hlm-backend || true
      - name: Run Selenium Tests
        run: mvn clean test -Dsurefire.suiteXmlFiles=testng.xml
      - name: Archive Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/
