name: Mirror Healenium Proxy to GHCR

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Login to Docker Hub (optional – if hitting rate limits)
      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Login to GHCR
      - name: GHCR login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      # Pull from Docker Hub, tag, and push to GHCR
      - name: Mirror image
        run: |
          VERSION=3.3.1
          IMAGE_NAME=healenium-proxy
          GHCR_REPO=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$VERSION

          docker pull healenium/proxy:$VERSION
          docker tag healenium/proxy:$VERSION $GHCR_REPO
          docker push $GHCR_REPO
